FROM bitnami/haproxy:2.8.2

COPY config/haproxy.cfg /bitnami/haproxy/conf/haproxy.cfg
COPY config/dataplaneapi.yaml /bitnami/haproxy/conf/dataplaneapi.yaml

USER root
RUN chown -R 1001:1001 /bitnami && \
    mkdir /etc/haproxy && \
    mkdir -p /var/run/haproxy && \
    chown -R 1001:1001 /var/run/haproxy && \
    chown -R 1001:1001 /etc/haproxy
USER 1001
